### ISSUE TITLE
Damage text is red by default

### ISSUE THREAD

**Issue by hoffersrc** [n0kk/ahud#101]
In the latest TF2 update with the newest unmodified version of ahud, the damage text fill above attacked enemies is red despite colors.res and huddamageaccount.res hashing identical to the previous version I had (Damage Numbers = 255 255 0 255 yellow). Notice the numbers above the HP look normal.

same results on both dx81 & dx95 with customized optimization configs
AMD FX-6300, no OC
Radeon HD 7770, no OC, driver package version 16.50.2011-161223a-310015C (old but runs tf2 best ime)
Win7 SP1 x64
d3d version 9.14.10.01235

![tr_rocket_shooting20002](https://user-images.githubusercontent.com/37904227/38091362-55e03f94-3333-11e8-8353-61ba7e00398b.jpg)

**Comment by n0kk** [comment]
They added an RGB slider in the Advanced Options with the latest updated. Look for Combat Text Red Channel, Combat Text Green Channel, and Combat Text Blue Channel. Likewise, the console commands for these are:

``` 
hud_combattext_green
hud_combattext_red
hud_combattext_blue
```

I'll look into seeing if they can be overrwritten through the HUD but for now set it in-game.

**Comment by hoffersrc** [comment]
That's the one update note I hadn't seen, interesting.
