### ISSUE TITLE
Next map results

### ISSUE THREAD

**Issue by h9lk** [n0kk/ahud#103]
Hi n0kk, thx for update hud, but sometimes he goes wrong
![20180331174153_1](https://user-images.githubusercontent.com/32390006/38165046-630ea338-3516-11e8-8444-4b4ece664006.jpg)
And don't see version your hud on tf2 main page
![20180404203137_1](https://user-images.githubusercontent.com/32390006/38323913-57ddafb6-3847-11e8-8d0d-29ddda6bd4dc.jpg)

**Comment by n0kk** [comment]
I've played several games of Casual on your resolution (1024x768) and I can't reproduce the map vote panel going off to the side of the screen as shown in your picture. I suspect this is the just the game behaving oddly, as some parts of the HUD can change with graphics changes while in game.

The version label is there on the bottom-right corner; the opacity for the label is just very low. You can open up the console or the menu while in a game and it should be more clear.

**Comment by h9lk** [comment]
thx
