### ISSUE TITLE
Tournament and newly added teammate health HUDs overlap

### ISSUE THREAD

**Issue by justinsamsel** [n0kk/ahud#104]
![20180411200939_1](https://user-images.githubusercontent.com/2882293/38655665-9f2246d6-3ddb-11e8-97c8-894c80ee8977.jpg)

**Comment by n0kk** [comment]
This occurs with the default HUD too. I don't think I'll be changing anything to the tournament setup panels as this is the classic position. For now, you can disable the match HUD with `tf_use_match_hud 0` while in tournament mode.

**Comment by justinsamsel** [comment]
Oh okay. I will do that. Thanks n0kk for all the work you do to create such an amazing HUD. You are very talented and appreciated.
