### ISSUE TITLE
Item Meter Labels Missing

### ISSUE THREAD

**Issue by bullyhunter** [n0kk/ahud#106]
For some weapons like spys watches the label on the meter is not visible when the meter is full.

**Comment by n0kk** [comment]
After the Jungle Inferno update (?) the color for the item meter labels became hardcoded to white, which unfortunately matches the filled meter for most items (aslo hardcoded afaik).

I'll test out adding a dropshadow which is the only reasonable workout I can think of, as I don't want to reposition the meter label to another place.
