### ISSUE TITLE
ahud glitch

### ISSUE THREAD

**Issue by Dextro360** [n0kk/ahud#115]
Everytime i go spy, try to disguise, the disguise kit always looks cut-off, it only shows the first 3 classes and the rest arent shown, i can still disguise as any of the class tho. Please fix, its the only problem i have with ahud, thank you very much.
![2019-01-05 3](https://user-images.githubusercontent.com/46393963/50721825-afe1e500-1100-11e9-9e46-2177d32c1748.png)

**Comment by peeballs90** [comment]
Same exact issue, its with all menus for me including so like engies hud n stuff
