### ISSUE TITLE
MVM Mission Complete view is broken

### ISSUE THREAD

**Issue by obayit** [n0kk/ahud#120]
after finishing an mvm game i get this
v2019.1218
![20200120195045_1](https://user-images.githubusercontent.com/20386024/72747946-b1246980-3bbe-11ea-916f-63b9cc8a052b.jpg)

**Comment by CriticalFlaw** [comment]
It's a known issue with multiple HUDs. You'd have to input `hud_reloadscheme` into console beforehand for the panel to display properly
