### ISSUE TITLE
UI scaling still broken after Scream Fortress 2024

### ISSUE THREAD

**Issue by Kurumesu** [n0kk/ahud#141]
Title pretty much says it all

**Comment by myria666** [comment]
Managed to fix party chat by replacing `log_font_small/medium/large` all with `HudFontSmallest`, but scoreboard remains a mystery. AFAIK, player names on scoreboard use the font Default. I've updated my `fonts.res`'s Default according to some suggested fixes but nothing seems to work. I've toyed with a few other fonts and I cannot seem to get it to work. For some reason, setting my game to be 4:3 1280x960 makes scoreboard work, albeit the font is tiny. No idea what's up with it.

**Comment by Kurumesu** [comment]
Closing since HUD hasn't been worked on since 2020, and most likely never will
