### ISSUE TITLE
MVM - (giant) robot health difficult to see 

### ISSUE THREAD

**Issue by HorseMD** [n0kk/ahud#21]
If a robot has health greater than 999, it is mostly unreadable (appears truncated at best).

I'm running Linux but a friend of mine who uses Windows has a similar problem.

**Comment by n0kk** [comment]
Does the health appear with an ellipsis, e.g. "10..."? If so, open up `healthiconpanel.res` in `resource\ui` and make the `wide` value for `HealthIcon` greater than what it currently is. It wouldn't hurt to make the `tall` value the same so it doesn't get cut off vertically as well.
