### ISSUE TITLE
Health box shows as red when I spawn

### ISSUE THREAD

**Issue by WiperTF2** [n0kk/ahud#23]
Screenshot: http://i.imgur.com/67GziwL.png

hud_reloadscheme fixes it temporarily, but obviously that's annoying to have to do every time. Any fixes?

**Comment by n0kk** [comment]
Common TF2 bug with almost every HUD. No fixes. I think it has to do with alt-tabbing out of the game and going back in.

**Comment by WiperTF2** [comment]
Thanks. I definitely do tab in and out of the game a lot so I suppose that's why.
