### ISSUE TITLE
Hunstman Pullback Charge Meter is COMPLETELY Broken.

### ISSUE THREAD

**Issue by dishsoap** [n0kk/ahud#24]
When modifying ahud, I noticed that there wasn't a hudbowcharge.res file, so I created one and made it to where I wanted to see if it would work. It did, but when I noticed it got stuck inside of another charge meter, I quickly tried to change it, nothing happened. I deleted the file and everything, kept modifying and all. Nothing has happened and the meter is still stuck inside of another charge meter. If there's another file that effects the huntsman or anything, please tell me so I can fix it.

http://imgur.com/9mJqiDO
LINK TO MY HUD CURRENTLY TO SEE WHAT I'M TALKING ABOUT.

**Comment by n0kk** [comment]
Yeah, for some reason the huntsman charge meter is also tied to `huddemomancharge.res` so I'd edit this file instead of using `hudbowcharge.res` (I actually think I had that file in ahud at one point and in the end it was was easier to remove it and work with the other file).

**Comment by dishsoap** [comment]
Okay thanks dude, I should be able to fix the problem I was having now. Thanks again.
