### ISSUE TITLE
Knockout powerup icon in Mannpower

### ISSUE THREAD

**Issue by ThePsionic** [n0kk/ahud#25]
In Mannpower, the icon for the Knockout powerup currently only shows the top-left of the icon rather than the entire icon. This can be seen at http://puu.sh/hO5Zz/23bec65442.png (as opposed to a well-working powerup: http://puu.sh/hO62n/dd72b9ad87.png)

**Comment by n0kk** [comment]
Both screenshots appear to be black on my end.

**Comment by ThePsionic** [comment]
Whoops, seems puu.sh doesn't correctly capture TF2. Should have checked before making the issue ;P
