### ISSUE TITLE
Forgot to mention needing to use "hud_reloadscheme" in order to refresh hud while working with crosshairs.

### ISSUE THREAD

**Issue by moonst0ne** [n0kk/ahud#26]
figured id give you a heads up before you get a bunch of the same question

**Comment by moonst0ne** [comment]
Also as a request, would the be anyway to add a subtle current team color indicator to the hub? A good example would be KBN Hud's tiny cross off to the side of health.
![cross](https://cloud.githubusercontent.com/assets/7356045/7794373/77cb7826-028f-11e5-8637-41a7d35b840f.jpg)

The reason I ask this is because I'm color blind as fuck and play with view model off, so it makes this a bit confusing at times when playing pubs and getting auto switched every round. Small gripe aside though the huds damn near perfect.

**Comment by n0kk** [comment]
Yes, just use this code in place of what's there now for `TargetIDBG` in `resource\ui\targetid.res`:

```
	"TargetIDBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"		"TargetIDBG"
		"xpos"			"0"
		"ypos"			"48"
		"zpos"			"-1"
		"wide"			"640"
		"tall"	 		"36"		
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/color_panel_brown"
		"scaleImage"		"1"
		"teambg_1"		"../hud/color_panel_brown"
		"teambg_2"		"../hud/color_panel_red"
		"teambg_3"		"../hud/color_panel_blu"
		"alpha"	"180"

		"src_corner_height"		"23"
		"src_corner_width"		"23"

		"draw_corner_width"		"0"
		"draw_corner_height" 	"0"
	}
```

**Comment by moonst0ne** [comment]
Just saw this and thanks for the help. Looking forward to the next update, whenever you get the time anyway.

**Comment by moonst0ne** [comment]
Hmm Ive tried both with hudplayerhealth regular and nobox but im not getting any difference as far as i can tell. both seem identical with normal and changed targetid settings.

Im running no box on most everything so could that be it?

**Comment by n0kk** [comment]
Should work regardless of whichever `hudplayerhealth.res` file you use; `targetid.res` is the same for both. I've tried it out and the team color bar appears for me below the health and name. Not sure what else I can do to help. Make sure you're replacing the original `TargetIDBG`
