### ISSUE TITLE
Few bugs!

### ISSUE THREAD

**Issue by LaMqTa** [n0kk/ahud#29]
Hello! I've updated my hud and i finally got the contracts working. Thanks! But i've got few problems with the Scoreboard. It does cut the ping. Also it's missing the pick button on the new items and it seems that the tf_hud_target_id_show_avatars is not working. Thanks.

http://imgur.com/a/kcPUf

**Comment by n0kk** [comment]
Yeah, ping getting cut off is a known issue. I've only done it in 1920x1080 and it works fine. I either have to sacrifice name width or I'm going to have to widen the scoreboard to compensate for other resolutions. I'll be experimenting with that soon. 

The pick-up button/icon on the TargetID I might just leave out for stylistic purposes. There are a couple of icons and a label that just won't fit in the small TargetID bar (and it doesn't help that some of these properties are locked and can't be moved via xpos and ypos). I may be able to just throw in the hand symbol. We'll see.

I've added the new `AvatarImage` property in `targetid.res` (not in the latest update), but I can't seem to make it display no matter what position or whichever `tf_hud_target_id_show_avatars` value. Will continue to find for a solution.

Thanks.
