### ISSUE TITLE
Backpack item quality color borders not working

### ISSUE THREAD

**Issue by qsvui** [n0kk/ahud#31]
A screenshot of my backpack:
http://i.imgur.com/JRvFXRM.jpg

For comparison, from the ahud imgur album:
http://i.imgur.com/GQobTQ2.jpg

The item quality colors aren't showing even though "Show Quality Color Borders" is enabled. All the weapons in my screenshot should have a yellow background. The yellow only appears when my mouse hovers over the weapon.

**Comment by n0kk** [comment]
With the new Gun Mettle Update that's something that broke. Valve broke something with the clientscheme, and there is a sort-of fix but the name gets hard to read in the backpack, so i'm gonna keep it the way it is now

**Comment by qsvui** [comment]
Looks like the default HUD changed it so that the edges of each box are colored, not the entire box as it was before. The entire box is still highlighted if you mouse over an item.

**Comment by qsvui** [comment]
Fixed by commit f93e6e16e527f22b21fff06fc45effc691afe1f2
