### ISSUE TITLE
mp_tournament_readymode 1

### ISSUE THREAD

**Issue by averagecomputerguy** [n0kk/ahud#35]
![image](https://cloud.githubusercontent.com/assets/3173124/9130147/842b4ab0-3ca5-11e5-9ccc-d2794ecc4f86.png)

When the cvar in the title is set on a server, the UI looks like this (white block covering the tournament hud). It'd be nice if you could fix it. :)

**Comment by LaMqTa** [comment]
I would also like a fix for this because more and more servers/pugs started using this and it might good if it works on ahud. (less huds have it fixed so it will give an advantage over the other huds huehueh) 

Thanks in advance!

**Comment by n0kk** [comment]
Added :+1:
