### ISSUE TITLE
Individual Ready up timer and more

### ISSUE THREAD

**Issue by LaMqTa** [n0kk/ahud#36]
Hey mate! First of all i have found that the individual ready-up timer is over the control point icons, might be good if you can move it somewhere else. Screenshot: ![screen1](https://cloud.githubusercontent.com/assets/8946189/9263507/5b0f6f18-4226-11e5-8e34-4078ddccfdcf.jpg)
 Also i feel like the players of the individual ready up should be smaller or somehow fixed because you can see here it looks great on 6s but imagine having 3 more on each team. It will be crowded or atleast for my res (1366x768) Screenshot: ![screen2](https://cloud.githubusercontent.com/assets/8946189/9263508/5b112fc4-4226-11e5-8f4a-c72ca603ab75.jpg)

Not really an issue, but maybe a suggestion. Thanks in advance! Keep it going.. <3

**Comment by n0kk** [comment]
Thanks for the suggestions. I'll definitely work on the readymode part more when more servers start implementing them and I have a chance to play and work on it.

**Comment by LaMqTa** [comment]
TF2Pickup.net started testing this so i guess you can go there and see ;) Thanks for the answer

**Comment by n0kk** [comment]
Countdown issue possibly fixed by commit https://github.com/n0kk/ahud/commit/f9c1c246cf11c0852531e2a713f98390f070801c (can't test it, but it's default values).

**Comment by LaMqTa** [comment]
Yup! Tested it and now the timer is in the center and its all good! :+1: Thanks!
