### ISSUE TITLE
Request in Loadout screen and MVM Issue

### ISSUE THREAD

**Issue by Just1s** [n0kk/ahud#40]
Hey, I've noticed a few minor things, but overall the hud is great :)

1. Could you add buttons to change between team colors in loadout screen?

2. And the issue would be that I can't see mvm giant robot hp, so was wondering is it a bug or something?

**Comment by n0kk** [comment]
1. This shouldn't be hard to add. It's a feature I was going to add a while ago, but completely forgot about it. 

2. Refer to Issue #21.

**Comment by Just1s** [comment]
Yeah I saw #21 but that was about number cut off. And at least for me I can't see any numbers that should show hp.

**Comment by n0kk** [comment]
I believe (correct me if I'm wrong) the health appears with floating health icons (enabled in Advanced Options or `tf_hud_target_id_disable_floating_health 1` in console). If you have the old style (health next to name in the Target ID), they won't appear.

**Comment by Just1s** [comment]
Yeah I have the old style.

Thanks for the quick answer.

**Comment by Just1s** [comment]
Oh also one more question, I enabled the floating hp but its way to the left. What do I need to edit to make it center?
It looks like that http://i.imgur.com/wPjVVjb.jpg

**Comment by n0kk** [comment]
Edit `healthicon.res` in `resource/ui` and change the `wide` value of `HealthIcon`. 44 is a good value before it starts to cut off.

**Comment by Just1s** [comment]
Thanks again. Before closing this, why is that value 120 by default if 44 makes it centered?

**Comment by n0kk** [comment]
It's been a while since I tested it, but a `wide` value of 44 is too small for MvM giant robot HP. It gets cut off. 120 was just an arbitrary number that I selected that worked. Unfortunately, changing the `xpos` value in `HealthIcon`, otherwise it would've been centered.

**Comment by Just1s** [comment]
Alright, understood.
