### ISSUE TITLE
scoreboard scrollbar size

### ISSUE THREAD

**Issue by katiepea** [n0kk/ahud#42]
Should the scoreboard type switch to 12x12 automatically if there's more than 6 players on a team? If so mine is not doing that, if not is there a way I can change the width of the scroll bars, or left justification of the font so the ping text isn't cut off as displayed in this image?

edit: I realize I can make the default scoreboard 12x12 with the console hudmin command, which is an acceptable solution, still sort of interested to know what the resource location is (if any) for the scrollbar size though.
http://i.imgur.com/ltet7Rs.png

**Comment by n0kk** [comment]
Besides toggling `cl_hud minmode`, you can also click on the Scoreboard button in the main menu. 
As far as the scrollbar size goes, I haven't thoroughly looked for where it might be, but it may be hardcoded. I'll revisit it again in the future. 

For a temporary solution, you can go to this line https://github.com/n0kk/ahud/blob/master/resource/ui/scoreboard.res#L18 in `scoreboard.res` and use a smaller value for `name_width` (and `name_width_minmode` if you plan to use the 6v6 scoreboard). It should move everything right of the names with it when you do.

**Comment by LaMqTa** [comment]
Sorry for bumping this up, but does Ahud support the new "mouse option" on the scoreboard? Like the one csgo have? tf_scoreboard_mouse_mode 1/2 

Thanks in advance! :)
