### ISSUE TITLE
Killstreak

### ISSUE THREAD

**Issue by katiepea** [n0kk/ahud#44]
Would it be difficult to add a killstreak counter and/or achievment tracker to be visible without having to hit tab to see it? I've seen other HUDs with this. Sorry if this isn't a good place for this question.

**Comment by n0kk** [comment]
Both these features are already visible on the HUD without having to hit tab: the Killstreak count is at the bottom left corner (next to the 3D player model if enabled) and you can add achievement trackers via the 2nd button from the left of the menu (looks like a star).
