### ISSUE TITLE
Improved game mode browser

### ISSUE THREAD

**Issue by reddit-is-fun** [n0kk/ahud#45]
You have streamlined the layout and improved the menus for mouse, but the game mode browser is still intact. I'd like to see all modes on the same page, now I have to scroll through 8 (+ random) pages to see everything.
Descriptions aren't that important, but maybe show them on hover?

**Comment by n0kk** [comment]
Are you talking about the Quickplay panel and scrolling through the game modes i.e., Control Points, King of the Hill, Invasion, etc.? As far as I know, you can't have them all display on a single page. You're stuck scrolling through each in the panel.

**Comment by reddit-is-fun** [comment]
Yes. I wasn't aware of the limitations.

@n0kk I also want ask in one go if it's possible to bypass the "introduction screens" that are shown after connecting to a server, before selecting a class. After 150 hours I still get those autoplaying videos sometimes.

**Comment by n0kk** [comment]
Nope, another limitation as far as I know. It's been brought up before (in this discussion)[http://steamcommunity.com/groups/ahud/discussions/0/521643320362482161/] and there's a possible bypass for the map info, but I've never seen it work.
