### ISSUE TITLE
All text look wierd

### ISSUE THREAD

**Issue by limjh16** [n0kk/ahud#46]
I know its not supported on a mac yet, however I hope you can solve this as I enjoy playing with this hud from my friend's com. All of the big text (hp, the big "ahud" text on main menu" are halved, meaning i can only see bottom half.

**Comment by n0kk** [comment]
https://github.com/n0kk/ahud/issues/2 

The values that person changed probably don't work anymore, but the concept is still the same. You want to make the tall value for the affected labels bigger, and then most likely change the ypos value as well. I can't help much further on my end.
