### ISSUE TITLE
Many many bugs

### ISSUE THREAD

**Issue by DatDrummerGuy** [n0kk/ahud#49]
Hello,
I installed the latest version of ahud on a friend's computer (I did not installed it on my pc yet, so it might be just with him), but there are many problems : text not changing colours when passing over with the mouse, black background on map loading and strange map name placement...
Thanks for answering ! :)

**Comment by Decimation** [comment]
Happens to me too except the text colors. I don't think these are bugs though. The black background seems intentional.

**Comment by DatDrummerGuy** [comment]
Well....he could have told us :'(

**Comment by DatDrummerGuy** [comment]
Oh, just saw the told it on the steam group.
Well, I don't know for the text colors tho, I'll try it on my pc as soon as possible.

**Comment by n0kk** [comment]
Can you specify where the text colors not changing happens?

**Comment by DatDrummerGuy** [comment]
Yes, in the main menu especially.

**Comment by n0kk** [comment]
That was changed and theres a yellow border on the left when you highlight over a button. Not a bug.

**Comment by DatDrummerGuy** [comment]
Ohhh okay sorry ^^ didn't notice that in the update notes. 
Amazing HUD by the way, thanks ! ;)
