### ISSUE TITLE
Duel Scoreboard Broken 

### ISSUE THREAD

**Issue by DatDrummerGuy** [n0kk/ahud#52]
I think we can't see the current state of the duel on the scoreboard with ahud.
Would be great if you could fix it.
Many thanks !
Have a great day :D

**Comment by n0kk** [comment]
It's not broken; it's been disabled since I redid the scoreboard long ago.
I need to get a dueling mini-game to be able to reposition the duel stats info. I may reenable it in the future, but it's not for certain.

**Comment by DatDrummerGuy** [comment]
Oh okay sorry. Do you want me to give you, or "borrow" you my dueling mini-game ? It's not a problem at all.

**Comment by n0kk** [comment]
I can get one easily. Thanks though I appreciate the offer.

**Comment by DatDrummerGuy** [comment]
Great, thanks ! 
Have a good day :)
