### ISSUE TITLE
Matchmaking End of Game Team Font

### ISSUE THREAD

**Issue by averagecomputerguy** [n0kk/ahud#57]
On some servers, team names and avatars are associated with the party leader. At the end of the round, the hud currently uses the default font for team names. I'm unable to provide a demo for this case.

![](http://puu.sh/nMgra/d123df4793.jpg)

**Comment by n0kk** [comment]
I believe this happens when both parties are 6 stacked (someone tell me if I'm wrong). The scoreboard also has different elements when this happens. I'll try to get a demo when this happens and correct it. Thanks.

**Comment by LaMqTa** [comment]
Hey guys, Sorry for bothering here, but i didn't want to open a new thread. I have found some more bugs aswell when teams were 6 players stacked. 
http://imgur.com/SvopHlx - As you can see, the winpanel was also bugged. The picture is somehow bugged. On the second picture you can see my avatar(team avatar?!) on top left, i think this is also bugged. The 3rd picture has no bugs, dunno why i have uploaded it but nvm.
