### ISSUE TITLE
2nd bug report spawning with low health in color behind health

### ISSUE THREAD

**Issue by smilegpt** [n0kk/ahud#59]
After spawning sometimes you have the low health background which is an annoyance as the only way to get rid of it is refresh your hud.
If you could update this that would be great.
Screenshot of what I am talking about
http://steamcommunity.com/sharedfiles/filedetails/?id=648533496

**Comment by averagecomputerguy** [comment]
That's a tf2 bug, not an ahud bug.

**Comment by smilegpt** [comment]
It only happens with ahud, all other huds tested work fine.

**Comment by averagecomputerguy** [comment]
It doesn't only happen with ahud, it happens with other huds as well. You just haven't tested them long enough.

**Comment by n0kk** [comment]
It's more prominent with my HUD because of the buff/low health background. On other HUDs, it's usually the number's that change colors that don't have the background square style. If you're alt-tabbing out of your game, this happens a lot. hud_reloadscheme is the only way to fix this.
