### ISSUE TITLE
Engineer building hud is now to the right of the screen instead of to the left

### ISSUE THREAD

**Issue by ajkeene99** [n0kk/ahud#60]
I believe since the latest update (March 18th), the building HUD has moved to the right side, and it's distracting to look to the right when you're so used to it being on the left.

http://prntscr.com/ahgrrm (Screenshot)

Thanks for keeping ahud updated throughout all the 1-2 day updates.

EDIT: Nevermind, I found the right file in hudlayout.res and changed it back to the left side.

**Comment by n0kk** [comment]
Yup, the change is intentional. I'll probably be releasing something soon where you'll be able to revert back to the original building positions via a quick copy and paste. Sorry! I know not everyone enjoys the sudden switch.

**Comment by ajkeene99** [comment]
Alright. I just didn't know if something broke after an update, since that's what usually happens. Having the option to switch would be nice though.

**Comment by ajkeene99** [comment]
I spent a while trying to mess with the xpos value and then realized you just had to switch r160 to l160 :P
