### ISSUE TITLE
Engineer building status overlaps with achievements progress

### ISSUE THREAD

**Issue by scriptHero** [n0kk/ahud#62]
Since 2016.0325, the default position of the engineer toolbar has been moved back to to the left, albeit a little higher.  Unfortunately, there is an issue where the toolbar overlaps with achievements displayed on the HUD.  This only applies when there are more than 2 achievements on the HUD.

Repositioning this to the original (lower) left-side should fix it.  Also, please provide a customization file for the right-side toolbar, as I find it less distracting.

Sorry for being so formal ;)

Notice: Will be providing a screenshot asap.

**Comment by n0kk** [comment]
Top left is unfortunately the only real good spot for the building status panel I can work with; if left back on the original left center position, it would overlap with the tournament spectator panel when you are dead. IMO the panels take priority over the achievement progress.

You can download the right-oriented building status panel from an older commit here on this GitHub. I won't be including it back officially.
