### ISSUE TITLE
Close livestreams menu by default

### ISSUE THREAD

**Issue by scriptHero** [n0kk/ahud#63]
When you start TF2 with ahud or press `Esc` ingame, you get that livestreams menu dangling under the alerts, and contracts buttons - good thought for placement!

I sometimes need to change my settings via the console and the livestreams menu gets in the way.  So out of convenience, can we close the menu whenever the menu is opened?

**Comment by n0kk** [comment]
Not to my knowledge. Valve made it so the streams panel always open by default unfortunately. If you're not using the streams panel, you can disable it in `mainmenuoverride.res`, or possibly reposition it.
