### ISSUE TITLE
Live streams, crosshairs, and main menu class images

### ISSUE THREAD

**Issue by 339683032** [n0kk/ahud#64]
Is there a way to stop the live stream window from opening automatically? Or is that not a hud setting?  Also, can the crosshairs be made dynamic (e.g. hitmarkers)? I tried something with `event DamagedPlayer` in `hudanimations_ahud.txt` but as I suck at hud editing, it didn't work. Finally, how can I get the class images back on the main menu? It feels empty without something there.

**Comment by scriptHero** [comment]
N0kk has replied on [my issue](https://github.com/n0kk/ahud/issues/63) that the livestreams menu is a Valve thing, and cannot be closed via the hud.

**Comment by n0kk** [comment]
There's no real way to have dynamic crosshairs in TF2 like you see in other games. Read more [here](http://www.teamfortress.tv/24797/dynamic-crosshair-possible).

For the class image on the main menu, go to `mainmenuoverride.res` and find `TFCharacterImage`. The default values are:
```
	"TFCharacterImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"TFCharacterImage"
		"xpos"			"c-250"
		"ypos"			"-80"
		"zpos"			"-99"
		"wide"			"600"
		"tall"			"600"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
	}
```

**Comment by 339683032** [comment]
Thanks for your help! I asked about the dynamic crosshair because I saw a gif that showed a spinning crosshair with hitmarkers on reddit ([here's the gif](https://gfycat.com/FixedQualifiedGartersnake)). The OP of the post said that those crosshairs came from toonhud, so I wondered if it was possible to port the crosshair over.

**Comment by n0kk** [comment]
That's a custom VTF crosshair using material proxies to achieve the spinning crosshair. You can find more info about it in [this guide](http://huds.tf/forum/showthread.php?tid=23) near the end of the 4th section. Can you port them over? I'm pretty sure you can, but I wouldn't know the precise steps to in doing so. That guide has links to a couple of examples with instructions though. 

The crosshairs in ahud (Knuckles Crosses) are fonts, so you can't really animate them in any fancy way like spinning. They only flash, i.e., they change color when damage is being dealt.

**Comment by 339683032** [comment]
Alright, I'll check the guide out. Thanks!
