### ISSUE TITLE
Not an issue, rather a request regarding licensing of ahud as a base for hud modifications

### ISSUE THREAD

**Issue by ghost** [n0kk/ahud#65]
Can I permission to upload my own customized ahud and share it with people? (With crediting you of course)I have had some elements added from various other huds to make my own hud exactly how I want it Below are the screenshots:
Normal health
http://steamcommunity.com/sharedfiles/filedetails/?id=672839996

Low health and ammo
http://steamcommunity.com/sharedfiles/filedetails/?id=672840007

Buffed health
http://steamcommunity.com/sharedfiles/filedetails/?id=672840019

Eve hud scoreboard
http://steamcommunity.com/sharedfiles/filedetails/?id=672840035

I also added some custom damage numbers and what not

**Comment by n0kk** [comment]
Of course. Anyone is free to share their modifications of my HUD, or anyone else's as far as I know. There's a specific thread on teamfortress.tv dedicated for this as well (HUD modifications).
