### ISSUE TITLE
Unidentified Troubles

### ISSUE THREAD

**Issue by Fiaco** [n0kk/ahud#66]
Hello,
Im not sure if this a HUD related issue or if its just the server related issues but Im facing some issues like unicode unidentified scoreboard and missing timer on servers. You will understand from the screenshots. Let me know if this is a server issue or HUD issue.
Update: But now it is appearing to me in all the servers. I just updated the HUD and it still persists.

Extra: (I will request you to add  "cl_crosshair_scale 0" in your README, apparently even when the crosshairs built into tf2 are disabled and custom crosshairs from your HUD are chosen, sometimes crosshairs from tf2 overlaps with the custom crosshairs from your HUD. I am not fully aware of the issue.)

![20160426124437_1](https://cloud.githubusercontent.com/assets/18677856/14815052/d13a412c-0bb1-11e6-8167-b8d1d687a8cb.jpg)

![20160426161618_1](https://cloud.githubusercontent.com/assets/18677856/14820640/2c9013da-0bd0-11e6-9cec-286ab70cf753.jpg)

As you can see neither the timer nor the scoreboard is fixed. 

Info:
Apparently latest update to ahud, I updated the HUD last week.
Windows 7 x64
nVidia Graphics Driver
No Damaged HUD files.
Occurance: 3 skial Servers

**Comment by n0kk** [comment]
The missing round timer is a Valve bug. Can't do much about it unfortunately. As mentioned in the Steam group announcement, I was aware of the broken winpanel and mentioned I would fix it for a future update. Fortunately, that update is out now so redownload the HUD for the fix.
