### ISSUE TITLE
Scoreboard Bug

### ISSUE THREAD

**Issue by Supernova0211** [n0kk/ahud#67]
Every time I hit tab to see the scoreboard, it lags quite a bit. Especially in the midst of battle I'll spam tab to see the scores and the game lags like crazy. Is this a problem on my end or no? Also I've never had this problem with any other HUD including rayshud, Eve HUD and the default.

**Comment by n0kk** [comment]
It's a Valve bug caused by yesterday's game update.

**Comment by Supernova0211** [comment]
Ohhh okay thanks.

**Comment by Supernova0211** [comment]
So do you think valve might fix it in the next update or...?

**Comment by Fiaco** [comment]
Irrelevent until valve until notices about the issue.
