### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by Supernova0211** [n0kk/ahud#68]
I have subtitles in my game, but when I downloaded this HUD half of the text is pushed off the screen. I never had this problem with any other HUD.

**Comment by n0kk** [comment]
What resolution are you playing on? There's a chance the captions will be cut off with longer messages on 4:3 resolution because of it's position on the HUD (right-hand side of ammo). You can reposition where the captions under `HudCloseCaption` in `scripts\hudlayout.res` to remedy this.

**Comment by Supernova0211** [comment]
I have a 1366 x 768 as my resolution and 16:9 for my aspect ratio.

**Comment by Supernova0211** [comment]
Also I'm not pro at editing things in huds manually so I don't think I'd be able to re-position the subtitles.
