### ISSUE TITLE
Mann Versus Machine Target ID

### ISSUE THREAD

**Issue by PlasmaPsychosis** [n0kk/ahud#70]
Whenever I play MvM, the health displayed for Giants doesn't fully appear. The numbers appear to be cut off (Something with 3300 Health appears as "33...", but then when the Giant takes damage, it sometimes displays the whole number, such as when it hits 3000 or 2800). I am curious as to what .res file(s) I should edit and what I should edit in those .res files(s).

**Comment by n0kk** [comment]
I explain this here: https://github.com/n0kk/ahud/issues/21
