### ISSUE TITLE
[SUPPORT] How to set a default HUD Background

### ISSUE THREAD

**Issue by Fiaco** [n0kk/ahud#71]
How do I set the existing ahud's ctf_doublecross as default HUD background and not let others show up.

**Comment by n0kk** [comment]
It's not ahud's background; it's the default background when there's a full moon. You'll have to find the file name within the game and a couple of files, most likely `mainmenuoverride.res` and `chapterbackgrounds.txt`. Sorry I don't have the exact steps memorized, but here's a really helpful tutorial on setting up custom backgrounds: https://steamcommunity.com/sharedfiles/filedetails/?id=300985049
