### ISSUE TITLE
Hud is not showing up  //   How to have a double crosshair?

### ISSUE THREAD

**Issue by Sox0** [n0kk/ahud#72]
I typically used the installer so bear in mind I'm new to editing this hud.

My hud is currently not showing damage numbers, health, ammo, or anything of that nature. However I do see a small rectangle at the upper left side of the screen, and it appears to have text in it. This might be a width/height problem however I don't know where to fix it. Google searches have given me irrelivant information on how to fix this problem.

Also, I know that on the installer you could have more then one crosshair enabled. After the previous problem is solved can someone tell me how to enable 2 crosshairs.

**Comment by n0kk** [comment]
I would do a clean install of the HUD again if you're having these problems; it also sounds like yours is out of date if you're seeing that rectangle.

For 2 custom crosshairs, open up `hudlayout.res` in `scripts`, find `KnucklesCrosses`, copy everything in it, paste it below it, and rename it `KnucklesCrosses2` or something similar (rename the `controlName` to match the new one as well). Now you can use a different crosshair.

**Comment by Sox0** [comment]
Okay thank you, I will try that.

**Comment by Sox0** [comment]
So I just got around to doing this cause I was doing finals, what should I name the control name to?

**Comment by Sox0** [comment]
KnucklesCrosses
	{
		"visible" 		"1"
		"enabled" 		"1"
		
		"labelText"		"w"
		
		"controlName"	"CExLabel"
		"fieldName"	 	"KnucklesCrosses"
		"zpos"			"0"
		"xpos" 		 	"c-25"
		"ypos" 		 	"c-25"
		"wide" 		 	"50"
		"tall" 		 	"50"
		
		"font"			"size:,outline:off"	// size: range 10-50
												// outline: on or off
		
		"textAlignment"	"center"
		"fgcolor" 		"Crosshair"
	}
		KnucklesCrosses
	{
		"visible" 		"1"
		"enabled" 		"1"
		
		"labelText"		"l"
		
		"controlName"	"CExLabel2"
		"fieldName"	 	"KnucklesCrosses"
		"zpos"			"0"
		"xpos" 		 	"c-25"
		"ypos" 		 	"c-25"
		"wide" 		 	"50"
		"tall" 		 	"50"
		
		"font"			"size:25,outline:off"	// size: range 10-50
												// outline: on or off
		
		"textAlignment"	"center"
		"fgcolor" 		"Crosshair"
	}

This is what I have, and all I have is a W on the screen, however the re download fixed the missing hud.

**Comment by Sox0** [comment]
This is what I'm seeing 

http://images.akamai.steamusercontent.com/ugc/264965513934953029/741B94EC57706DE4C15DA4EFE9711787DEA83306/
