### ISSUE TITLE
minmode version? (numbers hp, ammo, and other little stuff)

### ISSUE THREAD

**Issue by fuzky** [n0kk/ahud#73]
how about minmode version like a in rayshud (http://i.imgur.com/ky7cu1g.png) or some versions of garmen huds (example: beavern: https://www.youtube.com/watch?v=lTj_S13gsFo) for "oldschool" players

sry for english, i know about my bad knowledge :/

**Comment by n0kk** [comment]
I currently have no plans to do a minmode version of ahud. Sorry.
