### ISSUE TITLE
Double cross-hair follow up

### ISSUE THREAD

**Issue by Sox0** [n0kk/ahud#74]
I have been playing Overwatch for the past month so I haven't really been dealing with this cross hair issue. And I am getting no responses to my previous thread. 

		KnucklesCrosses
	{
		"visible" 		"1"
		"enabled" 		"1"
		
		"labelText"		"w"
		
		"controlName"	"CExLabel"
		"fieldName"	 	"KnucklesCrosses"
		"zpos"			"0"
		"xpos" 		 	"c-25"
		"ypos" 		 	"c-25"
		"wide" 		 	"50"
		"tall" 		 	"50"
		
		"font"			"size:30,outline:off"	// size: range 10-50
												// outline: on or off
		
		"textAlignment"	"center"
		"fgcolor" 		"Crosshair"
	}
		KnucklesCrosses2
	{
		"visible" 		"1"
		"enabled" 		"1"
		
		"labelText"		"l"
		
		"controlName"	"CExLabel"
		"fieldName"	 	"KnucklesCrosses"
		"zpos"			"0"
		"xpos" 		 	"c-25"
		"ypos" 		 	"c-25"
		"wide" 		 	"50"
		"tall" 		 	"50"
		
		"font"			"size:25,outline:off"	// size: range 10-50
												// outline: on or off
		
		"textAlignment"	"center"
		"fgcolor" 		"Crosshair"
	}

This is what I have, and all I have is a W and a large dot on the screen. I want the dot and I don't know if it's not picking up the w from the cross hair pack. (The lower case w)

This is what I'm seeing: http://images.akamai.steamusercontent.com/ugc/264965513934953029/741B94EC57706DE4C15DA4EFE9711787DEA83306/

**Comment by Sox0** [comment]
Update, changing the control name to CExLabel2 gets rid of the w and adds the correct crosshair for the w. However it makes the dot invisible.

**Comment by n0kk** [comment]
Keep `CExLabel` named the same and change the `fieldName` from `KnucklesCrosses` to `KnucklesCrosses2`.
