### ISSUE TITLE
Matchmaking dialog missing elements

### ISSUE THREAD

**Issue by qsvui** [n0kk/ahud#75]
The pop-up dialog on first entering the competitive menu is missing some elements.

Default dialog:
http://i.imgur.com/2Q5aZXL.jpg

Current ahud dialog:
http://i.imgur.com/ziYyhRq.jpg

Note that the checkbox and the "tour" button are missing. The dialog for casual mode seemed to have all the elements though.

**Comment by n0kk** [comment]
Thanks. I overlooked the file but it's a simple fix. I'll include it in the next update.
