### ISSUE TITLE
Incomplete scoreboard in Casual matchmaking

### ISSUE THREAD

**Issue by Kuannz** [n0kk/ahud#76]
The scoreboard in Casual matchmaking shows only 6 players but there are 12 players in each team. It's kind of broken and incomplete now.
I think it uses the same scoreboard in Competitive mode and needs to be fixed.

**Comment by n0kk** [comment]
Have you tried selecting the Scoreboard button on the menu? It switches between 6v6 and 12v12. If that's not the issue, take a screenshot of it reply back.

**Comment by Kuannz** [comment]
OK it's fixed by clicking the "Scoreboard" button. Sorry I didn't realize that switch button.
