### ISSUE TITLE
Matchmaking leaderboards rank windows missing

### ISSUE THREAD

**Issue by qsvui** [n0kk/ahud#77]
A window does not appear when you hover over someone's rank in the matchmaking lobby leaderboards (but the rank text still does).

Default HUD view:
http://i.imgur.com/svZgP6V.jpg

Current ahud view (I added the red circle):
http://i.imgur.com/J2nui7e.jpg

**Comment by n0kk** [comment]
Yeah I can replicate this as well on my end. Might have something to do with me putting in a blank VTF in a recent update. It's not a huge concern so I think I'll leave as is, but if its easily fixable I'll let ya know.
