### ISSUE TITLE
Centered Charge Meter: Medi Gun charge percentage gets stuck when switching to Vaccinator

### ISSUE THREAD

**Issue by Alamei** [n0kk/ahud#79]
I just ran into a weird bug with the Vaccinator using the centered charge meter customization: If you charge a standard (any non-vacc) medi gun partially, then switch over to vacc (either via dying or supply cabinet), a shadow of whatever charge percent the previous medi gun had when you swapped gets stuck on the HUD. Examples here:
[Standard Charge](http://i.imgur.com/bo4LBdC.jpg)
[Vacc Charge w/ Stuck Percentage](http://i.imgur.com/uUPfOli.jpg)

The stuck charge percentage even carries over when you switch back to a standard medi gun (making it look like you spawned with x% already charged) until you start healing a target again and it resets to 0%.

**Comment by n0kk** [comment]
Yeah this is a bug that's been around for a while. I forgot I updated the readme, but it mentioned this in an old iteration of it. Only way to really remedy this is if I don't use a shadow for the number, but with no shadow, it looks really flat and hard to see on certain maps. It's a trade off but I'd rather have a shadow and deal with this bug than no shadow at all.
