### ISSUE TITLE
Scoreboard stuck in 6v6 layout?

### ISSUE THREAD

**Issue by briancmoses** [n0kk/ahud#80]
I seem to have an issue where the scoreboard always seems to display the 6v6 scoreboard,  even if there's far more players on each team. Is there a way that I can force aHUD to use the default scoreboard?

**Comment by josuegaleas** [comment]
You might have `Enable Minimal Hud` selected in `Advanced Options`. I was having this problem too.

**Comment by n0kk** [comment]
There's a Scoreboard button on the menu that toggles scoreboard size.

**Comment by briancmoses** [comment]
Disabling the the "Enable Minimal HUD" selection in Advanced Options did the trick,  thank you!
