### ISSUE TITLE
Help with editing

### ISSUE THREAD

**Issue by R2D2Warrior** [n0kk/ahud#81]
With the new update, I've decided to add some buttons to the matchmaking screen for opening console, opening the backpack, and opening the server browser. I copied one of the image buttons from the main menu (the replay one) and changed the name/fieldname, image, and command for these buttons. That got me here:
![image](https://cloud.githubusercontent.com/assets/1594266/17157220/fad011fa-535b-11e6-8ddb-ead4060e2ca3.png)
For whatever reason, clicking on them doesn't execute the command, but still plays the "button pressed" sound as it should. I know that the backpack and server browser can be opened from this screen since you can open console with the `` ` `` button and type `open_charinfo` or `gamemenucommand openserverbrowser`.

<details>
<summary>This is what I added to the bottom of `lobbycontainerframe.res`: (click)</summary>
```
	"CustomButtonsBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"CustomButtonsBG"
		"xpos"			"c-27"
		"ypos"			"437"
		"wide"			"54"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"paintbackgrounnd" "1"
		"bgcolor_override"	"0 0 0 255"
	}

	"CustomItemsButton"
	{
		"ControlName"	"CExImageButton"
		"fieldName"		"CustomItemsButton"
		"xpos"			"c-24"
		"ypos"			"440"
		"zpos"			"3"
		"wide"			"14"
		"tall"			"14"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		""
		"font"			"NormalCode12"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"Command"		"engine open_charinfo"

		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
				
		"border_default"	"NoBorder"
		"border_armed"		"NoBorder"
		"paintbackground"	"0"
		
		"image_drawcolor"	"ahudWhite"
		"image_armedcolor"	"169 123 53 255"
		"SubImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"1"
			"ypos"			"1"
			"zpos"			"1"
			"wide"			"12"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"image"			"glyph_items"
			"scaleImage"	"1"
		}
	}

	"CustomConsoleButton"
	{
		"ControlName"	"CExImageButton"
		"fieldName"		"CustomConsoleButton"
		"xpos"			"c-7"
		"ypos"			"440"
		"zpos"			"3"
		"wide"			"14"
		"tall"			"14"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		""
		"font"			"NormalCode12"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"Command"		"engine toggleconsole"

		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
				
		"border_default"	"NoBorder"
		"border_armed"		"NoBorder"
		"paintbackground"	"0"
		
		"image_drawcolor"	"ahudWhite"
		"image_armedcolor"	"169 123 53 255"
		"SubImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"1"
			"ypos"			"1"
			"zpos"			"1"
			"wide"			"12"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"image"			"glyph_options"
			"scaleImage"	"1"
		}
	}

	"CustomServerBrowserButton"
	{
		"ControlName"	"CExImageButton"
		"fieldName"		"CustomServerBrowserButton"
		"xpos"			"c+10"
		"ypos"			"440"
		"zpos"			"3"
		"wide"			"14"
		"tall"			"14"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		""
		"font"			"NormalCode12"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"Command"		"OpenServerBrowser"

		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
				
		"border_default"	"NoBorder"
		"border_armed"		"NoBorder"
		"paintbackground"	"0"
		
		"image_drawcolor"	"ahudWhite"
		"image_armedcolor"	"169 123 53 255"
		"SubImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"1"
			"ypos"			"1"
			"zpos"			"1"
			"wide"			"12"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"image"			"glyph_server"
			"scaleImage"	"1"
		}
	}
```
</details>
Any help with making them work would be greatly appreciated.

P.S. How can I have the background behind those buttons match the background of the "Back" and "Start Search" buttons?

**Comment by n0kk** [comment]
While I haven't attempted it myself, I had a friend try it out just for the console button and he also found no success in being able to make the button to work. Everything appears correct. If I had to take a stab at it, I would guess that such commands can not work outside of the main/in-game menu (essentially controlled by the `mainmenuoverride` and `gamemenu` res files). I'll take a look at it when I can, but I see no errors at first glance.

I'm also perplexed from where that slightly lighter grey of those buttons is coming from, seeing as you have a `bgcolor_override` of `0 0 0 255`. Instead of a single custom background, change `paintbackground` to `1` and try `defaultBgColor_override` for each button (`armedBgColor_override` and `depressedBgColor_override` if you want them to change on hover and click).
