### ISSUE TITLE
Giftapult menu has colliding buttons

### ISSUE THREAD

**Issue by qsvui** [n0kk/ahud#82]
I tried using a giftapult and I noticed that the cancel button was overlapping with the next/prev buttons.

Current ahud (I added the red circle):
http://i.imgur.com/5jfx4z2.jpg

Default hud:
http://i.imgur.com/mLrvaP4.jpg

Also, the title of the page (Select the item to...) seems a bit too close to the checkbox and dropdown dialog.

**Comment by qsvui** [comment]
This issue affects menus for other tools, such as the name tag.

**Comment by n0kk** [comment]
Fixed https://github.com/n0kk/ahud/commit/b51979dcb0b19d971b53d92e11c9b219e71164d8
