### ISSUE TITLE
End of Casual game scoreboard busted?

### ISSUE THREAD

**Issue by Puoi1** [n0kk/ahud#85]
screenshot: http://prntscr.com/cn7b5b

**Comment by n0kk** [comment]
I've played about 4 or 5 casual games since updating and I can't reproduce that. Try a clean install or verify your game.

![matchsummary](https://cloud.githubusercontent.com/assets/5848203/18928186/b32cb4d8-8584-11e6-9796-6adacbdc9715.png)

**Comment by scriptHero** [comment]
no-repro.

**Comment by Nerdzzz** [comment]
This is happening to me too, and I won't be able to close the vote if the match was good box. I'll try those solutions.
