### ISSUE TITLE
Survey dialog box is transparent

### ISSUE THREAD

**Issue by qsvui** [n0kk/ahud#86]
The window for the survey that was implemented in the 10/12/2016 update is missing. Sorry I couldn't get a screenshot but it looked something like what was described in issue #77. The next time it happens I'll try to capture a screenshot.

**Comment by n0kk** [comment]
Yeah, the new HUD file `surveypanel_base.res` uses the border `MainMenuBGBorder`, which I replaced with a blank VTF in the border definitions (as mentioned in #77). Only reason I did this was to remove a panel in the casual matchmaking lobby that couldn't be removed normally. I'll fix this as soon as I can, but this replacement VTF *should* work as a temporary remedy

[blank.zip](https://github.com/n0kk/ahud/files/528842/blank.zip)

Just copy and replace it with the one in `materials\vgui\replay\thumbnails`. 

Let me know how it goes

**Comment by qsvui** [comment]
Here's a screenshot of the competitive leaderboards with this VTF:
http://i.imgur.com/fdrtqKY.jpg

I haven't seen anything wrong with the casual matchmaking screen yet. I will give an update when I get the survey.

**Comment by n0kk** [comment]
👍

**Comment by qsvui** [comment]
Here is a screenshot of the survey with this VTF:
http://i.imgur.com/lGXVtek.jpg

**Comment by n0kk** [comment]
Fixed in https://github.com/n0kk/ahud/commit/5ad216565ed4cb9484baecf1aa0d4f6e71977335.
