### ISSUE TITLE
Major FPS Drops

### ISSUE THREAD

**Issue by ItsHipsterNoah** [n0kk/ahud#87]
Hi @n0kk,

Ever since the update on October 12th, I've been experiencing major FPS drops or outright freezes when using ahud. I've never had this problem before, and it only started happening since the update.

I think the issue may be related to one that sigsegv posted on Reddit (link [here](https://www.reddit.com/r/tf2/comments/57760o/cause_and_fix_for_serious_fpsdrop_issue_involving/ target= _blank)). 

I tried his fix, which is basically removing everything under "event DamagedPlayer." I tested it in a bot match, and I no longer experienced FPS drops or freezes. I did not experience any visual issues with the HUD either.

There's a section for HUD developers as well to fix the issue, so feel free to look at that.

**Comment by n0kk** [comment]
Thanks for the heads up. Fixed in https://github.com/n0kk/ahud/commit/5ad216565ed4cb9484baecf1aa0d4f6e71977335.
