### ISSUE TITLE
Cant change scoreboard?

### ISSUE THREAD

**Issue by Lukas32** [n0kk/ahud#90]
Installed the hud normally, went in game and saw i had the 6v6 scoreboard(thought that 12v12 was the stock scoreboard here). Exited game, went to customizations and got the 16v16 board, went back in game and still nothing changed. I followed the instructions in the .txt file

**Comment by sergun26** [comment]
try to disable hud minmode
cl_hud_minmode 0

**Comment by Lukas32** [comment]
Just 6 months late, eh? XD Thx but I stopped playing tf2. Its become really
crappy cuz of those updates and lack there of + cheaters, bad balancing,
etc.

Dana 10. srp 2017. 11:33 osoba "Sergun" <notifications@github.com> napisala
je:
