### ISSUE TITLE
Text bug

### ISSUE THREAD

**Issue by Spuzaw** [n0kk/ahud#96]
Not sure where to post this so I posted here and on hud.tf.

Anyway, first I just want to say I absolutely love your HUD! 

I just ran into one problem. Below the ammo I can see this odd text. Think it says "ImageButton". And the same thing happens below the health but only when I'm low on health.

Here's an screenshot to show what I mean: https://i.imgur.com/T2w62cj.jpg

**Comment by Spuzaw** [comment]
Also, this is off topic but do you have a donation link or something?

**Comment by n0kk** [comment]
The buff/low health and low ammo boxes use a CExImageButton for the animation. What you're seeing is a button with no text, thus "CExImageButton" appearing. But that shouldn't happen. All the boxes have a textinsety of 99, which means the text is pushed down 99 units, way beyond the max height of 43 units of all boxes. 

Your health and ammo in clip numbers are also not their intended size. Something is probably getting resized. Is this on Windows or another OS? Non-Windows OS's have a weird way with rendering fonts sometimes.

In any case, you can try going to `resource\ui\`, opening`hudplayerhealth.res` and `hudammoweapons.res`, searching for HealthBoxBG and LowAmmoBG respectively, and changing the `textinsety` to a number much greater than 99. Adding a blank `labelText` could possibly work too.

I'm not taking donations but I appreciate the offer.

**Comment by Spuzaw** [comment]
Dude thanks! Your update fixed it! I just got home from work and I'm amazed to find out you already fixed it. That was a nice surprise!

Oh, and I'm using Windows 10 but I forgot to mention that I'm running the game in 4k with Nvidia's DSR. I'm guessing that must have caused the text to show up? 

Anyway, thanks again for fixing it! You by far have the best looking HUD in TF2. Looks sleek and professional. I will never use another HUD.
