### ISSUE TITLE
Display of сompetetive part

### ISSUE THREAD

**Issue by h9lk** [n0kk/ahud#98]
Hi n0kk, today i goto competitive and something goes wrong with hud

![default](https://user-images.githubusercontent.com/32390006/35123264-97df695e-fcb2-11e7-93ca-60e8bd8bb9f5.jpg)

**Comment by n0kk** [comment]
It should be fixed after [today's update](https://github.com/n0kk/ahud/commit/d079847d75b93c6ec2bd166f864ca17a5ad82be3).

Thanks for the head's up.
