### ISSUE TITLE
Crosshair Color Issue

### ISSUE THREAD

**Issue by ozmeister** [n0kk/ahud#99]
I've tried changing the color of the custom hud crosshair. I went to hudlayout and changed it to green, and it stays that way until i damage someone. I looked around and found that if i went to resource>scheme>colors i changed the crosshair color to "0 255 0 0" and the crosshair damage to "0 255 0 0" so it would stay the same color. Everytime after I damage someone, it always turns back to the default crosshair color, black. (Also I can't turn the crosshair damage marker off)

**Comment by ozmeister** [comment]
...

**Comment by n0kk** [comment]
Leave the fgcolor as `Crosshair` in `hudlayout.res` and change the Crosshair color in `resource\scheme\colors.res` to `0 255 0 255`. Leave CrosshairDamage untouched if you want default red damage flash, or the same as Crosshair for no damage flash.

**Comment by ozmeister** [comment]
Thanks, it worked.
